#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# config/routes.yaml

#create_transaction:
  #  path: /transaction/create-transaction
 #   controller: App\Controller\TransactionController::createTransaction
 #   methods: ['POST']
 
