#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

#get_budget_details:
#    path: /budget/api/budget
#    controller: App\Controller\BudgetController::getBudgetDetails
#    methods: ['GET']

